# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mhhod\Desktop\group14SE\demoMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 684)
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowFilePath("")
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 20, 779, 613))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 2)
        self.search = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 7, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cash_radioButton = QtWidgets.QRadioButton(self.widget)
        self.cash_radioButton.setObjectName("cash_radioButton")
        self.verticalLayout_4.addWidget(self.cash_radioButton)
        self.credit_radioButton = QtWidgets.QRadioButton(self.widget)
        self.credit_radioButton.setObjectName("credit_radioButton")
        self.verticalLayout_4.addWidget(self.credit_radioButton)
        self.check_radioButton = QtWidgets.QRadioButton(self.widget)
        self.check_radioButton.setObjectName("check_radioButton")
        self.verticalLayout_4.addWidget(self.check_radioButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cash_LineText = QtWidgets.QLineEdit(self.widget)
        self.cash_LineText.setObjectName("cash_LineText")
        self.verticalLayout_6.addWidget(self.cash_LineText)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.creditName_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.creditName_lineEdit.setObjectName("creditName_lineEdit")
        self.horizontalLayout_3.addWidget(self.creditName_lineEdit)
        self.creditNumber_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.creditNumber_lineEdit.setObjectName("creditNumber_lineEdit")
        self.horizontalLayout_3.addWidget(self.creditNumber_lineEdit)
        self.creditCSV_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.creditCSV_lineEdit.setObjectName("creditCSV_lineEdit")
        self.horizontalLayout_3.addWidget(self.creditCSV_lineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkHolder_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.checkHolder_lineEdit.setText("")
        self.checkHolder_lineEdit.setObjectName("checkHolder_lineEdit")
        self.horizontalLayout_5.addWidget(self.checkHolder_lineEdit)
        self.checkAccount_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.checkAccount_lineEdit.setObjectName("checkAccount_lineEdit")
        self.horizontalLayout_5.addWidget(self.checkAccount_lineEdit)
        self.checkPayTo_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.checkPayTo_lineEdit.setObjectName("checkPayTo_lineEdit")
        self.horizontalLayout_5.addWidget(self.checkPayTo_lineEdit)
        self.checkAmount_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.checkAmount_lineEdit.setObjectName("checkAmount_lineEdit")
        self.horizontalLayout_5.addWidget(self.checkAmount_lineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 2, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 800))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 6, 0, 1, 4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.searchID_radioButton = QtWidgets.QRadioButton(self.widget)
        self.searchID_radioButton.setObjectName("searchID_radioButton")
        self.verticalLayout_7.addWidget(self.searchID_radioButton)
        self.searchDate_radioButton = QtWidgets.QRadioButton(self.widget)
        self.searchDate_radioButton.setObjectName("searchDate_radioButton")
        self.verticalLayout_7.addWidget(self.searchDate_radioButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_8.addWidget(self.dateEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.purchase = QtWidgets.QPushButton(self.widget)
        self.purchase.setObjectName("purchase")
        self.horizontalLayout_2.addWidget(self.purchase, 0, QtCore.Qt.AlignBottom)
        self.quit = QtWidgets.QPushButton(self.widget)
        self.quit.setObjectName("quit")
        self.horizontalLayout_2.addWidget(self.quit, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shirt = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shirt.sizePolicy().hasHeightForWidth())
        self.shirt.setSizePolicy(sizePolicy)
        self.shirt.setTristate(False)
        self.shirt.setObjectName("shirt")
        self.verticalLayout_2.addWidget(self.shirt)
        self.pants = QtWidgets.QCheckBox(self.widget)
        self.pants.setObjectName("pants")
        self.verticalLayout_2.addWidget(self.pants)
        self.shoes = QtWidgets.QCheckBox(self.widget)
        self.shoes.setObjectName("shoes")
        self.verticalLayout_2.addWidget(self.shoes)
        self.hat = QtWidgets.QCheckBox(self.widget)
        self.hat.setObjectName("hat")
        self.verticalLayout_2.addWidget(self.hat)
        self.socks = QtWidgets.QCheckBox(self.widget)
        self.socks.setObjectName("socks")
        self.verticalLayout_2.addWidget(self.socks)
        self.jacket = QtWidgets.QCheckBox(self.widget)
        self.jacket.setObjectName("jacket")
        self.verticalLayout_2.addWidget(self.jacket)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.shirt_spinBox = QtWidgets.QSpinBox(self.widget)
        self.shirt_spinBox.setObjectName("shirt_spinBox")
        self.verticalLayout.addWidget(self.shirt_spinBox)
        self.pants_spinBox = QtWidgets.QSpinBox(self.widget)
        self.pants_spinBox.setObjectName("pants_spinBox")
        self.verticalLayout.addWidget(self.pants_spinBox)
        self.shoes_spinBox = QtWidgets.QSpinBox(self.widget)
        self.shoes_spinBox.setObjectName("shoes_spinBox")
        self.verticalLayout.addWidget(self.shoes_spinBox)
        self.hat_spinBox = QtWidgets.QSpinBox(self.widget)
        self.hat_spinBox.setObjectName("hat_spinBox")
        self.verticalLayout.addWidget(self.hat_spinBox)
        self.socks_spinBox = QtWidgets.QSpinBox(self.widget)
        self.socks_spinBox.setObjectName("socks_spinBox")
        self.verticalLayout.addWidget(self.socks_spinBox)
        self.jacket_spinBox = QtWidgets.QSpinBox(self.widget)
        self.jacket_spinBox.setObjectName("jacket_spinBox")
        self.verticalLayout.addWidget(self.jacket_spinBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.quit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Store Location"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Starkville"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Jackson"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Memphis"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Payment Information"))
        self.cash_radioButton.setText(_translate("MainWindow", "Cash"))
        self.credit_radioButton.setText(_translate("MainWindow", "Credt Card"))
        self.check_radioButton.setText(_translate("MainWindow", "Check"))
        self.cash_LineText.setPlaceholderText(_translate("MainWindow", "$ Cash amount"))
        self.creditName_lineEdit.setPlaceholderText(_translate("MainWindow", "Card holder"))
        self.creditNumber_lineEdit.setPlaceholderText(_translate("MainWindow", "Card number"))
        self.creditCSV_lineEdit.setPlaceholderText(_translate("MainWindow", "Security code"))
        self.checkHolder_lineEdit.setPlaceholderText(_translate("MainWindow", "Account name"))
        self.checkAccount_lineEdit.setPlaceholderText(_translate("MainWindow", "Account number"))
        self.checkPayTo_lineEdit.setPlaceholderText(_translate("MainWindow", "Pay to"))
        self.checkAmount_lineEdit.setPlaceholderText(_translate("MainWindow", "Check amount"))
        self.label_4.setText(_translate("MainWindow", "Search Type"))
        self.searchID_radioButton.setText(_translate("MainWindow", "Search by TransactionID"))
        self.searchDate_radioButton.setText(_translate("MainWindow", "Search by Transaction Date"))
        self.label_5.setText(_translate("MainWindow", "Search Criteria"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Transaction id..."))
        self.purchase.setText(_translate("MainWindow", "Purchase"))
        self.quit.setText(_translate("MainWindow", "Quit"))
        self.label.setText(_translate("MainWindow", "Inventory"))
        self.shirt.setText(_translate("MainWindow", "shirt"))
        self.pants.setText(_translate("MainWindow", "pants"))
        self.shoes.setText(_translate("MainWindow", "shoes"))
        self.hat.setText(_translate("MainWindow", "hat"))
        self.socks.setText(_translate("MainWindow", "socks"))
        self.jacket.setText(_translate("MainWindow", "jacket"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
